GET http://localhost:8080/books

###
POST http://localhost:8080/books
Content-Type: application/json

{
  "tile": "Clean Code",
  "author": "Robert C. Martin",
  "genre": "Software Engineering"
}

###
GET http://localhost:8080/books/2